{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  serviceName: {{ include "library-chart.fullname" . }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.git.enabled }}
        checksum/git: {{ include (print $.Template.BasePath "/configmap-git.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.oidc.enabled }}
        checksum/oidc: {{ include (print $.Template.BasePath "/configmap-oidc.yaml") . | sha256sum }}
        {{- end }}
        {{- if (include "library-chart.repository.enabled"  .) }}
        checksum/repository: {{ include (print $.Template.BasePath "/configmap-repository.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if not (empty (trim (include "library-chart.configMapMLFlow" .)))}}
        checksum/mlflow: {{ include (print $.Template.BasePath "/configmap-mlflow.yaml") . | sha256sum }}
        {{- end }}
        {{- if not (empty (trim (include "library-chart.configMapHive" .)))}}
        checksum/hive: {{ include (print $.Template.BasePath "/configmap-hive.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: home
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "library-chart.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.security.oauth2.enabled }}
        - {{ include "library-chart.oauth2ProxyVolume" . | indent 10 | trim }}
        {{- end }}
        {{- if .Values.discovery.hive }}
        - name: hive-config
          configMap:
            name: {{ include "library-chart.configMapNameHive" . }}
        {{- end }}
        {{- if .Values.discovery.metaflow }}
        - name: metaflow-config
          configMap:
            name: {{ include "library-chart.configMapNameMetaflow" . }}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.service.image.version }}"
          command: ["/bin/sh","-c"]
          {{- $authMethod := ternary "none" "password" .Values.security.oauth2.enabled }}
          args: ["{{ .Values.init.standardInitPath }} /usr/bin/code-server --host 0.0.0.0 --auth {{ $authMethod }} /home/coder/work"]
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          env:
            {{- if .Values.init.regionInit }}
            - name: REGION_INIT_SCRIPT
              value: {{ .Values.init.regionInit }}
            {{- end }}
            {{- if .Values.init.regionInitCheckSum }}
            - name: REGION_INIT_SCRIPT_CHECKSUM
              value: {{ .Values.init.regionInitCheckSum }}
            {{- end }}
            {{- if .Values.init.personalInit }}
            - name: PERSONAL_INIT_SCRIPT
              value: {{ .Values.init.personalInit }}
            {{- end }}
            {{- if .Values.init.personalInitArgs }}
            - name: PERSONAL_INIT_ARGS
              value: {{ .Values.init.personalInitArgs }}
            {{- end }}
            - name: PASSWORD
              value: ""
            - name: PROJECT_USER
              value: {{ .Values.environment.user }}
            - name: PROJECT_GROUP
              value: {{ .Values.environment.group }}
            - name: ROOT_PROJECT_DIRECTORY
              value: /home/{{ .Values.environment.user }}/work  
          envFrom:
            {{- if .Values.oidc.enabled }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameOidc" . }}
            {{- end }}
            {{- if .Values.git.enabled }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameGit" . }}
            {{- end }}
            {{- if (include "library-chart.repository.enabled"  .) }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameRepository" . }}
            {{- end }}
            {{- if not (empty (trim (include "library-chart.configMapMLFlow" .)))}}
            - configMapRef:
                name: {{ include "library-chart.configMapNameMLFlow" . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }} 
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/{{ .Values.environment.user}}/work
              name: home   
            {{- if .Values.discovery.hive }}
            - name: hive-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            {{- end }}   
            {{- if .Values.discovery.metaflow }}
            - name: metaflow-config
              mountPath: /home/{{ .Values.environment.user}}/.metaflowconfig/config.json
              subPath: config.json
            {{- end }}
            - mountPath: /dev/shm
              name: dshm
        {{- if .Values.security.oauth2.enabled }}
        - {{ include "library-chart.oauth2ProxyPod" . | indent 10 | trim }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
