{{- define "library-chart.deleteJobCron" -}}
{{ if .Values.deleteJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "library-chart.fullname" . }}
spec:
  schedule: "{{ .Values.deleteJob.cronMinuteAtDay }} {{ .Values.deleteJob.cronHourAtDay }} * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "library-chart.serviceAccountName" . }}-delete
          containers:
            - name: delete-job
              image: "europe-west4-docker.pkg.dev/artifact-registry-5n/dapla-lab-docker/helm-cli:{{ .Values.deleteJob.imageVersion }}"
              imagePullPolicy: IfNotPresent
              command:
                - helm
              args:
                - delete
                - {{ .Release.Name }}
          restartPolicy: OnFailure
{{- end }}
{{- end }}