{{ if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mageai.fullname" . }}-env
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.config | indent 2 }}
{{ end }}
