{{ if and (not .Values.existingSecret) (.Values.secrets) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mageai.secretName" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
stringData:
  {{ toYaml .Values.secrets | indent 2 }}
{{ end }}
