{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mageai.serviceAccountName" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mageai.fullname" . }}-job-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "delete", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mageai.fullname" . }}-job-manager
subjects:
- kind: ServiceAccount
  name: {{ include "mageai.serviceAccountName" . }}
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: {{ include "mageai.fullname" . }}-job-manager # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mageai.fullname" . }}-workspace-manager
rules:
- apiGroups: ["", "networking.k8s.io", "apps"] # "" indicates the core API group
  resources: ["nodes", "persistentvolumeclaims", "services", "statefulsets", "statefulsets/scale", "ingresses", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mageai.fullname" . }}-workspace-manager
subjects:
- kind: ServiceAccount
  name: {{ include "mageai.serviceAccountName" . }}
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: {{ include "mageai.fullname" . }}-workspace-manager # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
