{{- if .Values.security.oauth2.enabled }}
# Should be moved to library-charts
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-client-config
data:
  oauth2-proxy-client-config.yaml: |-
      provider = "azure"

      # This will restrict login to accounts with email address in the
      # configured domain.
      email_domains = ["ssb.no"]

      # Request "standard" scopes from Keycloak.
      scope = "openid email profile"


      # The <addr>:<port> to listen on for HTTP/HTTPS clients.
      http_address = "0.0.0.0:4180"

      # Url(s) of the upstream endpoint. If multiple, routing is based on path.
      # Does not work with "hostname" based ruting.
      upstreams = ["http://127.0.0.1:{{ .Values.networking.service.port}}"]

      ## Headers

      # Passing of OIDC ID-Token to upstream in a Authorization Bearer header.
      pass_authorization_header = true

      # Passing the request Host Header to upstream. If set to "false" the
      # host of the upstream will be used.
      pass_host_header = true

      # Passing HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email
      # information to upstream.
      pass_basic_auth = false

      # Passing Oauth access_token to upstream via X-Forwarded-Access-Token
      # header.
      pass_access_token = false

      ## Cookie settings

      # Base name of cookies to store tokens.
      cookie_name = "oauth2_proxy"

      # Generate a random encryption key for encrypting the cookies (AES) to ensures
      # that only "this" client can read the cookies containing the tokens.
      cookie_secret = ""

      # An active session can be max 8 hours long.
      cookie_expire = "8h"

      # Refresh cookies and tokens after max 10 minutes. This value should be larger
      # than the expiry of the access token and probably less than "cookie_expire".
      cookie_refresh = "10m"

      # HTTPS only cookies.
      cookie_secure = true

      # Not available to Javascript.
      cookie_httponly = true

      ## skip SSL checking for HTTPS requests
      ssl_insecure_skip_verify = true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy
spec:
  encryptedData:
    client-id: AgBsZRJx0nzRAuqEtRq/QWrVWZsENvgGJwhRAuof2KBDjOl71eaNhOVvJvcnHgTHPHuJzsYMlmEqC/a1ZbInTuiR3fWgjKGjopIi3w+T77ZfFLwmII5wvCpR/xe+NKCTUVHHRZHpNwuxznnheulF4jO2e4/VF0Jy/0HgMKrruwk4kJ31UEWFdMcnMMRwarVC94rugyJWsX4fIIwZjlzo/p7twn/M9vXg88t1O01njj83hP2CvM25p7RS042SE0WcOsCOvorLcGip2CScDi7hPVV3oLzW/JVtGfP4blMHxT29pBnb5r7h0mxUdt1QFxx578atJZwY38Cqq1TKmVBHLjntNNcqTLXz8/5YwNEALGedDbIUTOIDmOoTfTggrUBxjoe3JQpACp6S3+dqJhP9ddyQhfKioVs4XVtSR3+iJZql3o+1rx2AWh0JGpSxJiEIYvX9ppr85tjuLFbO+9X5/dzqW9mY4xWh7dYm/9uths9UUMSv2mUtlFnWxRXI/cYJ6XZ4ZknyfW/CBD39HosaviLX5qwSyNRiWIT7xHIDKMWiDiA7HZ3SZp9jcZVMYkEvzGPenULhlBL38IqVkRJFc8UxgMfKaqi6XdmOzKoBEF+KoZPHIblCp3VsCDseL8TKCqmPiYvRZ3j3TbHMuBlhNeOxjK0LPZtSGipweLYXYOpiXydhA6S4NSvuzJwiMPwRxp0Emx+wjH0YLdf4l8Twal2001URDYY59cERnvtjUmZIAQ5cA/E=
    client-secret: AgAfXM+EHW9o6V7JcwCzeMnMLIYJEBYrW5TAxPCWRq03779r12zPrpsW9XDmHrF8FJZ1LiKNUIW91HmcMdP6UTE8QxCslYcajt7ialOGu5GG1BO+M1WCteLVrTNlpRoxrq4YKtm/WwJcFDNltPd+PrczmRkoCV26O6EmCyIEAvQOS215iW6F4np1hfRtkA7mH1ifTyeGav7rddRNsWrnNs8NapgNAATX2x/VMl5KubtxuLAhFcWYUwhjQne1kOGbzRW7Xa1Yb24qVHD4LP34fns6xbURP5fLRCusVhD00bzNJNbfJ6BXg0KXGKmDk3oU5lbM4ARISNnbDG8ZchyG1cvQpXEiT6+CSFfb7h1R9Pek2m9pElIAtF3HVoPBemUXoBwnNFIbpchquMBqkqQAyHCMkIcACFn9O1qS+qNrHJvQmvue9Y/CkzNBBZK6Uqcg+xVZZgH6I5zrRGL/HVyk3J+rz3C1Y63mQM7bhnELiuJq5S8lLrywv/kU1BXORdBiF2madi8AAgxgxv8b6HFB/j/HeyYtkGH9ST8MCWBpFiVcmHmNadgOA1jzSMYf/FUgWYbFoj5CaLP0JEPfT+oQLnKCHJZIWg2IY2EgKDImMWrk5GlblMSgPAkKpimFiNiDuQht5f7p1DgeMMRWZeMXW1Dse272FYNTxFmIhTsUy8nd9Cfk46cHrKx9cwbslYwWm1PdkUnbsRl6Tc7Pw7k71JfkfxziNGgSJd7BiR8yPpIcP3W3o6+B9BNN
    cookie-secret: AgBfrBGTG6/PJcCY+PEYCt7EAtXwe6P7IMOj8VQPwAR/Y/q11J4Ywoj64ou1Zo4N2Wmw9P6JJCBt8//oScAXDmg4co9TNMJk5lgdutPcQerPHSEFhgf2a6rvSbhkjdCiGLQ1+JvDZP4Y8QOgy1jQ67ZeGv6mNcf0HOJA+GEPd1wShsadNLL+peW+DI36Zm1vpIpZB/SeH1IYIztVANh1c6W9jblII0E2YsYlNfQCFKBilcwfe16+AKvvUc+ms3jS8U/0Ii2Vji3hVjN3PuoGcArjm9ocvpkTnRu4f/6m0HF2XGKXorCBRVmEr+haa48gC8jSm54IgX+gUAagV8LF1a7/deOGk1VJmQkptYi9vi/F23OEmyh0qV1zTueDIKTqx/75Icejg35Vz/7SLNhEh0qNF8h4QymEvJxPEpQMIeHRWEqkACB3nPqhsqL3KbfpdSYTpNImZJGSWcwN74oqVMORpavXCH5Ap+wQGr7tQGJ3CFkMeYldj4Xi93T9YuMqfi6dxQbyrfU7dsR10+UNFFUmo5aSt3Y5SZwz/QaMR6NlXy09fQTf3bBf8ySjOXpp9k1jYyf61VuPAhsXrpAAtJ/rGsifu7kCT97wO98DoIJoSw1Lp8JOqli6c1g9JSB5qAOw0LRA0s2AzbwESAmMyFBzVYNvtwhPSFK7DZmKytcikjISxCeG3GVPAVoVWn3i4d8sONC1n9DpAsCeAP41sI9fqhm1ZgyQXaIQszHA8+3RzwNnY08xM8D9wKUaKw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy

{{ end }}