{{- if .Values.security.oauth2.enabled }}
# Should be moved to library-charts
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-client-config-{{ include "library-chart.fullname" . }}
data:
  oauth2-proxy-client-config.yaml: |-
      provider = "google"


      # This will restrict login to accounts with email address in the
      # configured domain.
      email_domains = [*]

      # Request "standard" scopes from Keycloak.
      scope = "openid email profile"


      # The <addr>:<port> to listen on for HTTP/HTTPS clients.
      http_address = "0.0.0.0:4180"

      # Url(s) of the upstream endpoint. If multiple, routing is based on path.
      # Does not work with "hostname" based ruting.
      upstreams = ["http://127.0.0.1:{{ .Values.networking.service.port}}"]

      ## Headers

      # Passing of OIDC ID-Token to upstream in a Authorization Bearer header.
      pass_authorization_header = true

      # Passing the request Host Header to upstream. If set to "false" the
      # host of the upstream will be used.
      pass_host_header = true

      # Passing HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email
      # information to upstream.
      pass_basic_auth = false

      # Passing Oauth access_token to upstream via X-Forwarded-Access-Token
      # header.
      pass_access_token = false

      ## Cookie settings

      # Base name of cookies to store tokens.
      cookie_name = "oauth2_proxy"

      # Generate a random encryption key for encrypting the cookies (AES) to ensures
      # that only "this" client can read the cookies containing the tokens.
      cookie_secret = ""

      # An active session can be max 8 hours long.
      cookie_expire = "8h"

      # Refresh cookies and tokens after max 10 minutes. This value should be larger
      # than the expiry of the access token and probably less than "cookie_expire".
      cookie_refresh = "10m"

      # HTTPS only cookies.
      cookie_secure = true

      # Not available to Javascript.
      cookie_httponly = true

      ## skip SSL checking for HTTPS requests
      ssl_insecure_skip_verify = true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy
spec:
  encryptedData:
    client-id: AgAJcHlMaXuj92hxORu4mmq+2FFhOeFZfSkk3Vf58OebOs42IwUwx5gBckOnPLQjScQAmgmiiw/DgXOL5hf3e5yJwnXQ9+REmAPDByQtdKBeVSbKJjvmdFyGrJ7s+4PWx5VutNfHqqvwimDaLlnorRef6gtLSTC0ECP+Inw+1yLqLg2ZKlvgm8gHqsZ/dW/zl/7lm6AREz0i9epavoAp+0GAAoZ50KAYZ2IlD8D5QGxDbt/5hbac31fLZLfsH4nWQ0/z5GTcCE52ojYHRpSmeMAuL6xTbdHOFNXNDEISFvXphoHsAaU2BX3d2cPLhgd0RUgZ9k7W+naMr21PgbXJ2Az3POTp+84Idv3gJt8uH4o7foRbcZO9ndJBjHH3Vdbp1ta78VmLvMnSKYQ1MGPL0Jc0S5dl/dr47O8iQLOVcS0DjbDapjlj7/vgDL0rfJ75Li+HarF3dDJuLyypJdnf3UOSP6p+cEw73p1aOpRGYE/UvFT2lxCgAsBB2jvYt1GVF+/FtZYsK860NbIC88eTP6GiwWjDX9ruMR7k2Bll4bpcQWfIh+uyIJVlUq3K9v0BKpDiJwIeNPNglgTTnzXY/iW2PLSmgW1+5YSARgL/pXGEqEZDADqC/xSpVPvWPcbg8rxoH8V4cOcEY6UG+Ndum6ExU6MuYjjtwp7srXdUNNkrkrKnRfQX/DKU+pQ02l4+zI+TOPJAuS7yGGVMYUYPMG5yj/QzGsAPaLMyAcIn21JtAS/6z0M=
    client-secret: AgClmXe7R+G0GWs6USMHENkCC8V2+lJ8B1iVnyfB6HSaB4ZVLgrSWStvHBOs2aZLtC4EL8qeo/IZDyJbaniUDQ/NvgLwNuV+LVk6cRKjHUigNBc2X6rSJI7LIRHNy+sai2z5dG0CFYq6BqCFU4iyEdZpxCSRkyam8lIfo/c+dayfCh/7/yO7eV0UHse+tf0kllY7ZcCc2+labz7zE39Uryk8nvlfgldSMBvU1yCjLkATHEq0WlZ73NUpg1SFioOQ586DZi7uUWX13tOY1xjsajJb0xj6e7/7t4kIXV67bg8whkvZrkVvVA/1U/qxDQQrYueJLbVsujYYHMcZMSbn8rwPjJPZWlWFpOzNRVQcXsNBAL/STAUKVppl0hGoBvKmOrAVUpVUy+faxwC+p1Ho22zR1dNB6BIOfPodGEcAiSEzBapZYINpA42I4WzAcRdvxl223Sp728uOY+UOhyrd1SnHNSeP9KLezlUhfXRV5cc0/ZNDvvGlTmWL2YZvYuz6I9L9sYyKCyxRYAyJL1JUrPu+/bOOdiCou62xKO7COq1AZj2c4kVEID3fyT4/Dvs1e9/TuaOf6ukrUEkEDnlUtJPDLxBh5qrFUEU1C6nR8fmwxzIIflgeQJrbokB0niMjhFE3Sfw7qWIFo0xEc5WucXCDNj0PeC+yK8ppwHRcW3PeetiYMWPYSIJekIsSa5YOsec6sLSltshvNClaWyCARXDw7Uaq6n0rsMuLk/mv1LqicioDcjMODDXY
    cookie-secret: AgAfnItkjza3xIg4PIlq6GNiMUTRacyXiV/Lhe07Q/awA/RP/PUe0GY7eU0WqvZYE+2g1DEsP1nOswbrJvz3Xl7t4fH9ElYLfX7GeZwWnpZ5m3HJABP92M2YFPtzHvd/xzynKafskcRFp6xWEXVD+QNpvsw3eU3H4/aOIZDxd+qq/tPJe2UkD8fULr8wXTRtaGg4yMjDnqX4X4skQe3xP2XhtbIj78/wqs2z9t8I4xU4yE5dK/cU8fz7ZeiIXZ4H54sLXEVfDGEK6PcsaZHam+KHRtg1mR1wlSH3EEQBjnVoeAAAEdNlLrOA1z910txLPH9TP65ABREGKs2zb0Gh1PqDO+npOaUdl0mb8MWMWMqQR6dWBR7Y5bStwn0wX0o76jLPGfS634skPiZ739Palf1nRhipwzmLShtjJ8o1wU8xYQODDkYIDrmNMBnl7lqfipiXXVI1xgHCnQYy0WNZiwgbXgrVZytHB0D0KG9qH/ZeM7NxoGpQRWcJXbCI74KWw+LQj9rJFVj7uLTgyvlRurG7YKfDyETJG/d0DlsP2sgqdDiBh5CliPHR1hYqF3ugKGoXAsy0bzWeSU5Sucrh614XLW+tGRRQHOxfpy3EVe5ypDILGV1MOC5sgOGqYhFnFtWjV59HJOKc1IGLrxMJefsjXLDoy66RrnmoVf4Rgp+82pP2oDhejvpjb6b/4onh06laYJcYtqbDhmF8zKFa+Wpg2x49t3dclIv9/Axrh5KNKsA+qnnXRpKfFY2n3g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy

{{- end }}