{{- if .Values.security.oauth2.enabled }}
# Should be moved to library-charts
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-client-config-{{ include "library-chart.fullname" . }}
data:
  oauth2-proxy-client-config.yaml: |-
      provider = "google"

      # This will restrict login to accounts with email address in the
      # configured domain.
      email_domains = "*"

      # Request "standard" scopes from Keycloak.
      scope = "openid email profile"

      # The <addr>:<port> to listen on for HTTP/HTTPS clients.
      http_address = "0.0.0.0:4180"

      # Url(s) of the upstream endpoint. If multiple, routing is based on path.
      # Does not work with "hostname" based ruting.
      upstreams = ["http://127.0.0.1:{{ .Values.networking.service.port}}"]

      ## Headers

      # Passing of OIDC ID-Token to upstream in a Authorization Bearer header.
      pass_authorization_header = true

      # Passing the request Host Header to upstream. If set to "false" the
      # host of the upstream will be used.
      pass_host_header = true

      # Passing HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email
      # information to upstream.
      pass_basic_auth = false

      # Passing Oauth access_token to upstream via X-Forwarded-Access-Token
      # header.
      pass_access_token = false

      ## Cookie settings

      # Base name of cookies to store tokens.
      cookie_name = "oauth2_proxy"

      # Generate a random encryption key for encrypting the cookies (AES) to ensures
      # that only "this" client can read the cookies containing the tokens.
      cookie_secret = ""

      # An active session can be max 8 hours long.
      cookie_expire = "8h"

      # Refresh cookies and tokens after max 10 minutes. This value should be larger
      # than the expiry of the access token and probably less than "cookie_expire".
      cookie_refresh = "10m"

      # HTTPS only cookies.
      cookie_secure = true

      # Not available to Javascript.
      cookie_httponly = true

      ## skip SSL checking for HTTPS requests
      ssl_insecure_skip_verify = true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy-{{ include "library-chart.fullname" . }}
spec:
  encryptedData:
    client-id: AgApKAnOpo897ewwysFXvuW+8HWCUaZbQmG+qT/q2Wxkf2YQE/Tc9UKO7t0IXaqp8qGsj+Y5ohn6p3U9cOKX/r4zt25n+GZqZNXDNW/8nlIw9cd8lWKgkd6iHPyq+ujGniou6sbUCjoubET138cmHSa1DRwSlZt/5Z8q/U7qmduMrmJcdPq3Ymv60hP+t+cR5fsxT6/7ktrerzO2pNT0cUjHvbC9tAQwc/pmhbJzPDJSDOYqYN7m+STHBabyVtVkWlkxLl9TyzheCQsMv0SOadItkBywAfP0eIT90ymKeA7fbt3NaHW9ibRsg9Qqid9aAvypW+rd1nTf53zg9hyuugvEIiZ9KAuLhXBHKlRobFEElNBXBdiH/7jDaIz+DrEtvmizm38ChcrIDDZatKbeD4qr8GtOQd2T5xHEUij4apl2fggt9iwBBYwpyH+IiptZGDox47Y0JU2UpR+hAunEV1Qcb+P6ywHLkQE2yiWDFmYdmWt92kstwuTFHwONgWL6zsZtzq3ex6iZ/yxkcNaA+cAVg4MGpjBbz2dM0VfGsH0OU+WAB1fCLo722nkNalz0iXrivAzLjGqi2UgCbXtnWH1RPIQw0B8LEBa20PNNO/CVHCcElf1KBY3D53/UB2sFSqIJuxMnlWGCtLV09wvUNdRjzaQyFERQ9y/WCKA2HyU0xtdm0cQeXpYtALIHR3kgJg4nElKSwMoaKukQz6xxgz+MWcpVbLR3T3hXgEKzMkl2dbgCH6bssmCAAWBjN+B04BkXwMGwfg9OCU9ylW9sUQWJuwxrpoDtKz5+
    client-secret: AgARLMv458vwA93nZRkRVNUbUalJnsMdyKX3CQpyg1MDGDc6WNiC2S/FugxOQgy4m5ikoFFS0D9QcKIE69/HjpcMaAVt46LfTb1jjm5W8fFk+QdIsqzStxQCwtjq4hgr/8bRNyljigHGK450eB7NSRONpzgP+4GEJrQXAsLzZaIxxgctqcjdb6BNUqEpxcxAriiqVRBy+YQUhd0hPMrvPCdd80bEbU538EU8iAPPeHhfAQXWb26115socB6RyJaSL1niJs7o8ZO1JxmOrojGOWTiIKc1jWUe5qfR7fX5XoJZKJbVKTs2ND5iPThfnurDoy/cdsMn0NDo4Nc+KjzBfSPxv7DyXxPntOBZV/m7GnejiVIB8zF9qqNO240txSW2Vrk11EPoN+6iI4irjny7GAoSg15EKdbQyLjq61gHX3Na8LS1AAmq7wlHMnuzYdKd8B8SGH5vx/EO4Ys+UWMXx6OvMpk7dxPaPTeW3YHdFCQXKOQbkp9K7pkEhTPO59LBxP2DB7WfzgRDq3hs+GDI2xoEkLAwU2O/0+4SQUcYHkMl4wtenLcPnya6yx4a27pKKBZbIoLgqYccsIvesWSaALRlk/OabXhO+nA+vPXzBkuEWkEFDmVmi9WUBCJzchnBvGx3Zgcl2jr81EZ4HZ8/eeU2KBt56OeVyr8sxeUk5bY+Sjc539c1RUByiXYabOPy/KbAJBCYaN4xZAggeZ2/QcG7WTy2EMkWFL+3A6CWTH2sgKy7jak=
    cookie-secret: AgAvgKG1e0XjFhzBM991IzzFVIpF7MqtrhRgMW9i5E4W0gu2cmRKO6wLdhW9p8dxosUR+kHu/fWQwsOlZFFSLplgIKPN8b/rNWeiga+rDf5KSlO5/+y6uC8B+cN5o0Wj9+qKpLzYiee0vDZCT1n/FWtSHE1UBbFgS4gzJ84GuwdeDZQuYYapfjCvSfsS0gGkrYegtEVVmrNDLMQNd9ILgxzOckmC/h6ahjipoPeppcYAg64HHUNtJI7jjFzoPH22RG05fGGnjPXRt21AbZopCZ4POKzLQARot2hMHrKVaGIyX8wpJxOrmbLu+DD4k/vvvJpzomfVPJSazK4ZNJt3oUwCWI04y2RaN01MTdz/RGSlCQp3875o6QZqxFIE+9H7bwI6ZWkzeps+eaR9ntBtelVgT1GgCtoH1NDdSnr97ll3BssT3hjC76L4winV1sokzGhyrT4ciJh14X9Te6xu34iXN8Ygtds9WGgIRNrp0z9HHXOpg23UTqj2DCQDvEamaSf57gP+ARP6RNH36ef18FvePrlJoXH281jSRg/25oCZCZG7Gt2RQllkLilV2LcxATUOQAM+vKVK8M/L1Yu5EfYcWcaE2NdON+c3YjwKKvGqPs98XmHbGG3bZ0e+kC8ES2ndxHiP4lyLXf4+PfcVIvRT6OoU9N9dlbq3EOBMSCB3JmSX6M8Ud/RUv2L41Bvi27fp/XC0a3T0DzlAlBkge3uuw7Z4ldMvIwmwJthznfwmgys8U10TYQUp54Dh2A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy

{{- end }}