{{- if .Values.security.oauth2.enabled }}
# Should be moved to library-charts
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-client-config-{{ include "library-chart.fullname" . }}
data:
  oauth2-proxy-client-config.yaml: |-
      provider = "azure"

        # OpenID Connect issuer URL.
      oidc_issuer_url = "https://login.microsoftonline.com/c7217092-b240-4e1d-bd61-fa97ba975cbc/v2.0"

        # Tenant ID for Microsoft IdP (Azure AD)
      azure_tenant = "c7217092-b240-4e1d-bd61-fa97ba975cbc"

      # This will restrict login to accounts with email address in the
      # configured domain.
      email_domains = ["ssb.no"]

      # Request "standard" scopes from Keycloak.
      scope = "openid email profile"


      # The <addr>:<port> to listen on for HTTP/HTTPS clients.
      http_address = "0.0.0.0:4180"

      # Url(s) of the upstream endpoint. If multiple, routing is based on path.
      # Does not work with "hostname" based ruting.
      upstreams = ["http://127.0.0.1:{{ .Values.networking.service.port}}"]

      ## Headers

      # Passing of OIDC ID-Token to upstream in a Authorization Bearer header.
      pass_authorization_header = true

      # Passing the request Host Header to upstream. If set to "false" the
      # host of the upstream will be used.
      pass_host_header = true

      # Passing HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email
      # information to upstream.
      pass_basic_auth = false

      # Passing Oauth access_token to upstream via X-Forwarded-Access-Token
      # header.
      pass_access_token = false

      ## Cookie settings

      # Base name of cookies to store tokens.
      cookie_name = "oauth2_proxy"

      # Generate a random encryption key for encrypting the cookies (AES) to ensures
      # that only "this" client can read the cookies containing the tokens.
      cookie_secret = ""

      # An active session can be max 8 hours long.
      cookie_expire = "8h"

      # Refresh cookies and tokens after max 10 minutes. This value should be larger
      # than the expiry of the access token and probably less than "cookie_expire".
      cookie_refresh = "10m"

      # HTTPS only cookies.
      cookie_secure = true

      # Not available to Javascript.
      cookie_httponly = true

      ## skip SSL checking for HTTPS requests
      ssl_insecure_skip_verify = true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy-{{ include "library-chart.fullname" . }}
spec:
  encryptedData:
    client-id: AgCZdvFVxitx6antGJSl+hynUA+FwEw6HH9MBmF537rIsSUa5vb7yHZXXYv+4yRrPVWu/CBomCe4IOdtrUjdyiSDP3tUc0VNd6N7KmbjdZERV9g6ddpNK88IDfGDGSeef1DH1HgnGpQeCMAu1llSzl9pMTlA5bmrqPqEJReYM1EyrUf50C0W21S7vlaG2XMcomAKwcwYVZC2YoPPpPQSRwGytQ7jYlW7hER1pWE/YCRwkEqeIJwBqz/C/RbUCLU31gAT78UjS2BjXPKuorghr7Dy2H1w8THzi5IWELr7zsisMqaIWkVvbnOQDDMjrkIe4w8SW0UkHFkrCPKeq3/CN4ZjfiBIXkj7bfbFDx0uBwk/LZrrVy3gD2FnsVgTmSDplyF2kUQj1/Yv05gwvs/UxcJpWjngSGJ88Ct9AdxHxch/cBnHdBzNO5dv26KcvxRMEUTF0OB3bjWP0PJAyYK3d77A8Iwcxis1x7r9+B/CxVxZZZhOPfIWvH+ZSsWw/xn7pj/Jpf9TaOQ/P8Ig/+7mQX7IIGfzO399net5aFlLPAyiPM03JscbumjndedvnxUY3yzA/YoqdJqF6P9SRlTx+eOY/GbVZAPNKsZq3bnK7xfGL1tiV+vcKM/pJnk0axn3rjSDhyvmROhvnSVuK8LtvL/F/P3deL05da7rlqaljFMuSSY6P0689Wb325gerlJSOcYLxjIHhfALb7X2k0jm2QWYD0Zro4daKmEaVQF9wHAuRviaDFo=
    client-secret: AgBsmqVWKL9yeCrTGQteYSYEeYPjUXLzIej50NjqtZufZvYvdKOWaCYMwFu3TMHoCofl13OdL5nzedvHcPm1510nX7WJSoeSGYekv+RHgphdAsRm9KtSUdiognPleenwG4oazECKJlTB+6iatHsginRgxk94l2oSN447iCu876q9BCkJsCmDfV1vo8chy4MFvjWAeCIcYHy4fR3m8ixII73pbKkVYXjZHwg5OiGzIN0PW1BWLJMyKqmzDBtYdu3XVzxx3kz1eV9M2YREahrdmfdAuSE0fulLePZqbhoJ7HlsmlBchq9v1OkypD6ZZfIHdu4zA0Px54zQ8JU2Fb0Jcb1o7wDSkhtXQwSKAkE8UQciRQ2md7cUufLy8YC9riOnT+Bme+XTFclDm3iOKSJgBvHz6TSKNyZTnF5ej8cqDYP916n6FjydKs2iFp3ZTYddXn1N5Ih4BsKUnIVaGl+y23NXD+lUz1O7hGsaLb30qAeINclXyNdyAXmLiDAF7gc9OdQZ39MmCCoKRiR4Tqz0HpAAcszprZhdyZTvYNFQTeh2Re4TNqLggHSoZDB1EEXVenf01SWRkQnD2qYixKaq5OxrTr91e2vXfcQeGalrVWyDExYyYltHSZQAxIOGuKZMLbmLIcZTxemJlRQuI5ncQi8oFnQPzIK7aFcmGQ0JezEOSwCVP2o8XJ9Jb0wOgco2BC4q537OnLtGkC03TQ7kS7D6V9bMQWm2s4774oOyFoGqkI2K+wc6Nj+7
    cookie-secret: AgArOOcjSG0j+dVm8fdpuDhIOx3bJmu9doexnpI4P/NZwGhlNzZXQR4m5cYdMCbuI6qdW/fnPcGjCGrURYIxa4n2/M1Vc53p3f1cyoKTiWBfxn5cNfzuNNnLJCiFwJFtHZuM//e6212hAjqnVcAs0oXzsb7ZjisEb45crWahSJgqA5l/C0WhWs8H2YK7YUAJl8aoodKPmnSJ065YP2i924hwWtEHn8XbGWH6KDoG89ru7zdUUGXZtR6nvmHAb43nmKHQYzIgPc6TIIHdYkHtgt0jMSDxy205Re0SbaAvx40bGubAvqj1rOpw18TxEvl+c1l+JVhpTW/+TKeGpocBnkaziC12nmO8LqB2yD2jiQDVtJ/NMQZJuyyEYSR28v/iwoqKotl+ZsZQsHyj0URNEg4Tp09iEfeqHIN8PPs/mh2aLtEY9mxSx28EY/EbCDeHwcSzYCEawqJITm8wXO2gN+32uvaI9pQPZtwUHZgUjDzH8i2HFhPckwQkyppECld5yne/ji4c8Shw/0eDFQbCMduYI60Tw8lo+19Dm8oJl5YHl7e/lIkMfB4croKAl+HFONwlS5qdlbE2QA0CZQnnQTHqXzoeAVELkDA2fpWSH0x3LvYAObT/3T0I75ypOkUj4Xwk+SfxatCdJ35qQGgJ0nT98SsFDAZ8oAfKEjp6uapARgid2lfk6hBwf80HD4KpC9A0bUYiNon03Xf9n1atz/QGxemJdd9+UPSjwImMCFjc86pWqFGp/fxn7sLWxQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy

{{- end }}